export enum Specialities {
  CARDIOLOGIA = 'CARDIOLOGIA',
  DERMATOLOGIA = 'DERMATOLOGIA',
  GASTROENTEROLOGIA = 'GASTROENTEROLOGIA',
  NEUROLOGIA = 'NEUROLOGIA',
  OFTALMOLOGIA = 'OFTALMOLOGIA',
  ONCOLOGIA = 'ONCOLOGIA',
  PEDIATRIA = 'PEDIATRIA',
  PSIQUIATRIA = 'PSIQUIATRIA',
  TRAUMATOLOGIA = 'TRAUMATOLOGIA',
  UROLOGIA = 'UROLOGIA'
}

